### ISSUE TITLE
queue_monitor_length notifying is platform dependent enforced since eos 4.25.4M

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1005]
## Issue Type

- [ ] Bug Report
- [x] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

With latest EOS 4.25.4M all NON-Jericho platforms refuse the LANZ command „queue-monitor length notifying“ because it is not supported on these platforms (e.g 7050X3, 7368X4,..).
Former EOS versions accepted this at all although it was not supported.

```
queue_monitor_length:
  log: < seconds >
  notifying: < true | false >
```

## Component Name
eos_cli_config_gen

## Steps to reproduce

queue_monitor_length:
  log: 5
  notifying: true

```yaml

```

### Expected results

Any kind of switch platform dependend decision in the AVDs if this can be rendered or not based on the hardware platform type. 

```shell
$
```

### Actual results

CVP gives the error message:
>queue-monitor length notifying % Unavailable command (not supported on this hardware platform)

```shell

```

**Comment by ClausHolbechArista** [comment]
We can work around this using some new `platform_setting` in `eos_designs`. We will not be able to address this directly in `eos_cli_config_gen`, since there is no concept of configuration validation. We can add a comment to the knob in the documentation, specifying that it is not supported on all platforms.
