### ISSUE TITLE
`eos_validate_state` should not rely on `eos_designs` variable `type`

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1047]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

In `eos_validate_state` the template `generate_vars_for_testing.j2` tests for `hostvars[node].type == 'l3leaf'`.
This variable is only set when using eos_designs, so we should not rely on it for tests.

Also with AVD 3.0.0 we will make the `type` value customizable, so we should not rely on that, to decide on reachability tests.

## Component Name 
`arista.avd.validate_state`

First new version will be `arista.avd.validate_state_preview` and only when it is complete and ready, it will replace `arista.avd.validate_state`

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ClausHolbechArista** [comment]
`eos_validate_state` should only rely on `eos_cli_config_gen` data model.

**Comment by xaviramon** [comment]
I can work on this one.

There are some assumptions that we need to do in order to solve this bug.

This is partially solved by PR#1360 https://github.com/aristanetworks/ansible-avd/pull/1360/files

If we assume all devices should be able to ping the VXLAN source interface and the Router-ID defined for all devices, that should be ok. If we need to add more intelligence, we will need to discuss.
