### ISSUE TITLE
structured_configuration beyond just eos_designs

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1083]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

I personally use group_vars associated to a device's region, site, or function to inherit structured_configuration for eos_cli_config_gen with either passing l3ls_evpn fabric structured_config from eos_designs or when generating my own per device configurations.  It would be useful to capture all relevant keys that eos_cli_config_gen could use in facts/vars for a current device and output it to a structured_config output for tracking in git along with the actual config.  Unfortunately, the current structured_config output by eos_designs only captures keys that eos_designs currently supports, and not what eos_cli_config_gen supports.

**Describe the solution you'd like**

Create a structured_config output task for eos_cli_config_gen following similar logic to eos_designs.

**Describe alternatives you've considered**

Appending relevant keys to the avd structure_config fact and outputting via my own task.

**Additional context**

**Comment by ClausHolbechArista** [comment]
I have had similar thoughts, but with a slightly different use case. Detect `eos_cli_config_gen`-supported keys as part of `eos_designs` and combine with those instead of overwriting. This should lower the amount of needed `custom_structured_configuration_` settings. These would all be included in `structured_config`.

Short term you can set your variables with a `custom_structured_configuration_` prefix (customizable as well), and set the `templates` key to only run the template for custom_structured_configuration. This will make `eos_designs` only do what you need.
For the final solution, we will need to have (and maintain) a schema of some kind, to identify the supported keys. This is only on very early planning phase, since we need to take a balanced choice between maintainability, ease of use, robustness, data validations etc.

**Comment by ryanmerolle** [comment]
@ClausHolbechArista good idea.  

I figured if `custom_structured_configuration_<some key not set by eos_design>` would not work since the key would not exist.  What am I missing here?

**Comment by ClausHolbechArista** [comment]
Keys set with `custom_structured_configuration_` prefix will be carried over to the `structured_config` even if they are unused/unknown to `eos_designs`.

**Comment by ryanmerolle** [comment]
great!!!!!!

**Comment by ryanmerolle** [comment]
The only annoying thing is I need to loop through a the dictionary of `base_config` using dict2items to create a new var with `{ 'custom_structured_configuration_' ~ item.key :  item.value }}`

**Comment by ClausHolbechArista** [comment]
Understood.
Try renaming `base_config` to `structured_config`.

This dict will also be combined into `structured_configuration`.

**Comment by ClausHolbechArista** [comment]
@ryanmerolle is there anything we need to do on this, or has it been addressed?
