### ISSUE TITLE
Interface description should be flexible

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#1131]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

I would like to be able to add a user-configurable TAG in the description of the fabric interfaces.

**Describe the solution you'd like**

User should be able to create a tag that will be added to description field in all fabric interfaces.
Example:
```
user_defined_tag: "MONITOR_THIS_INTF"
```
The output should be:
```
hostname LEAF-1A
interface Ethernet1
description P2P_LINK_TO_SPINE01_Ethernet1 MONITOR_THIS_INTF
(...)
```

**Describe alternatives you've considered**

Maybe we can create some "custom_structure" style that modifies some parameters after all execution? But this must allow also to reuse current values in structures.

**Additional context**

Some monitoring tools check the interface description and if they find an specific string in the field and the interface is down, are able to generate an alarm into another system. Specially useful in Day-2 operations.

**Comment by gusmb** [comment]
I also find this feature useful. I would suggest that the interface description for P2P uplinks (L3 and L2) are fully customizable based on customer needs. Some times it might be a text with tags, sometimes key/value pairs for monitoring systems (e.g., type=uplink peer=xxx monitor=true) or maybe a random text that follows certain pattern.

In any case, the most suitable way would be to add default templates for interface descriptions using the currently hard codes logic, so that they can be overriden by custom templated providing own customer logic.

To work with custom structure data on these templates, maybe adding support for "structured_config" at the uplink management part I. Fabric topology would help...

**Comment by gusmb** [comment]
Hi,
PR above with my proposal for interface description customization. I considered more than just P2P uplinks following similar patterns. Added the capability to provide custom templates for P2P uplinks leveraging contextual attributes (link.*) and switch facts (switch.struct_cfg could be leveraged to pass custom structured data like monitoring tags). See https://github.com/gusmb/ansible-avd/blob/issue1131/custom-interface-descriptions-uplinks/ansible_collections/arista/avd/roles/eos_designs/doc/extending-avd/node-types.md

Further details in #1156.
