### ISSUE TITLE
Management eAPI ACL configuration not applied

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1157]
### Issue Summary

When configuring the following ACL in the common vars:
```
			  #management eAPI
			  management_api_http:
			     enable_http: false
			     enable_https: true
			     enable_vrfs:
			       MGMT:
			          access_group: CVP-ACL <-----
					  
			  standard_access_lists:
			    CVP-ACL:
			      sequence_numbers:
			        10:
			          action: "permit 0.0.0.0/0"/https
```

The configuration generated does not apply the ACL, although it is generated:

```
management api http-commands
   protocol https
   no shutdown
   !
   vrf MGMT
      no shutdown

ip access-list standard CVP-ACL
   10 permit 0.0.0.0/0
```

Documentation: https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Configure any ACL to the eAPI as shown previously in the Fabric.yml, but it does not get applied.
```

### Relevant log output

```shell
debug vars for any leaf correctly show the ACL but then config is not generated:

management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    MGMT:
      access_group: CVP-ACL
```
```


### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
I believe this could be the reason:
* The structured_config directory has 2 yml files: <inventory_hostname>-debug-vars.yml   and   <inventory_hostname>.yml
* I checked both the files and found config for management_api_http:-
1) <inventory_hostname>.yml
management_api_http:
  enable_vrfs:
    MGMT: {} 
2) <inventory_hostname>-debug-vars.yml
management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    MGMT:
      access_group: CVP-ACL

But the first configuration was taken when eos cli configuration was generated, may be due to the yaml_templates_to_facts action not being able to discard null elements. 
I came to this conclusion after I debugged the tasks of eos_designs and eos_cli_config_gen.

Still looking in to the issue. Any suggestions!!

**Comment by tgodaA** [comment]
It isn't a bug. But need to use the below configuration to make it work ==>

```yaml
custom_structured_configuration_management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    MGMT:
      access_group: CVP-ACL
```

By default this snippet will over-ride any default configuration of **management_api_http**. This behavior can be changed by using the command: custom_structured_configuration_list_merge: < replace (default) | append | keep | prepend | append_rp | prepend_rp >

Reference: https://avd.sh/en/releases-v3.x.x/roles/eos_designs/doc/l3ls-evpn/common-settings.html#custom-eos-structured-configuration

**Comment by tgodaA** [comment]
Issue is solved by using custom_structured_configuration_management_api_http 
![image](https://user-images.githubusercontent.com/88734745/130798241-bc2f27c4-38ed-4767-849e-930fa7c7083e.png)
