### ISSUE TITLE
ansible fatal error using custom_structured_configuration_vlan_interfaces

### ISSUE THREAD

**Issue by ninnux** [aristanetworks/ansible-avd#2071]
### Issue Summary

When I try to use this configuration in host_var dir I have an ansible failure as you can see in "Relevant log output"
It seems to be impacted documentation generation only.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
using AVD 3.7.0 (AVD 3.0.0 is not affected)
using a host_var file with this text:

custom_structured_configuration_vlan_interfaces:
  Vlan1009:
   description: "JumpHost"
   ip_address: 10.0.9.253/24
   isis_enable: "EVPN_UNDERLAY"  <----- this line seems to be relevant (without that line no failure)
   isis_metric: 1000
```

### Relevant log output

```shell
TASK [arista.avd.eos_cli_config_gen : Generate device documentation] *************************
fatal: [RM_LEAF1 -> localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'mode' is undefined
  
    The error appears to be in '/usr/users/xxxx/.ansible/collections/ansible_collections/arista/avd/roles/eos_cli_config_gen/tasks/main.yml': line 46, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Generate device documentation
      ^ here
ok: [RM_SPINE1 -> localhost]
ok: [RM_SPINE2 -> localhost]
ok: [RM_LEAF2 -> localhost]
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello @ninnux 

looking at the current code I think this is indeed where you hit the problem:

https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/vlan-interfaces.j2#L153

Basically when `isis_enabled` is present, the template for documentation expects that either `isis_network_point_to_point` or `isis_passive` is set - the logic looks a a bit shady though as in either case, the default value for "mode" would end up being `-` though this bit of the code can never be accessed.
By comparison the template generating the configuration does not make such a dependency that's why it is passing.

PR to address this #2076.
