### ISSUE TITLE
Missing Daemon Attr Flag

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2214]
### Enhancement summary

Add support to render daemon attr flag `-cvcompression=gzip` in `eos_cli_config_gen`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to configure additional flag. See following link for list of commonly used flags:

https://aristanetworks.force.com/AristaCommunity/s/article/terminattr-most-commonly-used-flags-and-sample-configurations

### Describe the solution you would like

Add following key to the daemon_terminattr data model:

cvcompression: < none | gzip >

### Describe alternatives you have considered

using raw eos_cli, not ideal

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Hi Gustavo, This flag is no longer needed on TerminAttr, since it is always set inside the agent. What is your use case for needing this to be set specifically?
Adding @noredistribution, since he was the author of both the article and the templates/data models in AVD :)

**Comment by noredistribution** [comment]
That is right, we do not need this and haven't needed this for 3 years, which is why I've put a note inside the article as well

`Note that compression is enabled by default since TerminAttr 1.6.1 and CVP 2019.1.0 and it’s redundant to specify it in the daemon configuration.`

Some old builders might still have that in CV, but we've been removing them there too.

**Comment by gusmb** [comment]
Thanks both for the clarification. Closing the issue
