### ISSUE TITLE
Feat(eos_cli_config_gen & eos_designs) update PTP syntax from "enable" to "enabled"

### ISSUE THREAD

**Issue by nielsjlarsen** [aristanetworks/ansible-avd#2366]
### Enhancement summary

Currently, in v3.8.0 there's a discrepancy where in most places, PTP is enabled using the keyword "enabled", but in a few key places the keyword "enable" is used.
This is primarily due to historic reasons and changing it is thus a breaking change.
Since we're now looking into v4.0, this breaking change will be incorporated.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

In general (global, node or node_group) configuration, PTP is enabled using the keyword "enabled".
For connected_endpoints PTP is enabled using the keyword "enable".
For core_interfaces PTP is enabled using the keyword "ptp_enable".
For l3_edge PTP is enabled using the keyword "ptp_enable".

### Describe the solution you would like

The keyword / syntax to enable PTP should be "enabled" everywhere so copy/paste mistakes and confusion are avoided.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
~Please make sure that all code accepts both new an old. New should take precedence. Then we will deprecate the old in 4.0 and remove it in 5.0~ Since this will go into 4.0, we can implement this as a breaking change. Just remember to add it to the release notes section and link to details in porting guide.
