### ISSUE TITLE
Adding support for Hardware settings

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#3485]
### Enhancement summary

In the cli hardware section there are several options:
```
  access-list        Hardware parameter related to access-list
  capacity           Capacity and usage of hardware resources
  clocking           Clocking related component
  counter            Counter
  fabric             Fabric card configuration
  fec                Forward Equivalence Class configuration
  fpga               Field-programmable gate array
  nat                Hardware parameters related to NAT
  port-group         Port-group of QSFP or SFP ports
  speed-group        Hardware speed group
  system-controller  System Management
  tcam               Configure TCAM contents
```
  
  Specifically I was hoping to set the asset-tag section using AVD

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

Something that could look like this:
```
hardware:
  asset-tag:
    switch: <STRING>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The `hardware asset-tag` is not a configuration command. 
The command is available outside of the configuration mode, and even though EOS would accept this command in configuration mode, it is not stored as part of the configuration.

The issue here is that AVD generates configuration, and this configuration is often previewed on devices using config sessions where no changes are done to the device. If we included this command in the configuration, such a preview would in fact be changing the asset-tag without the user knowing.

The config session preview function is also part of the CloudVision workflow.

For now the only solution is to use the [`arista.eos.eos_command`](https://docs.ansible.com/ansible/latest/collections/arista/eos/eos_command_module.html#ansible-collections-arista-eos-eos-command-module) module to configure this on the device.
