### ISSUE TITLE
dot1x unauthorized access|native vlan membership egress to ethernet interfaces via port_profile

### ISSUE THREAD

**Issue by CyrielRct** [aristanetworks/ansible-avd#3765]
### Issue Summary

The following command have been added to ethernet_interfaces in cli_config_gen with #2826 

```
ethernet_interfaces:
  - name: <str>
     dot1x:
       unauthorized:
         access_vlan_membership_egress: <bool>
         native_vlan_membership_egress: <bool>
```

When defined in port_profile we get the following error : 

```
Validation Error: port_profiles[1].dot1x': Unexpected key(s) 'unauthorized' found indict.
```

My current understanding is when it have been added in ethernet_interfaces it haven't been added in port_profiles too. The interesting things here, despite the warning during the build, the configuration on interface is applied anyway. 

Current version of AVD : 4.6.0

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
1-Define a port_profiles

 - profile: PP-DOT1X
    dot1x:
      port_control: auto
      reauthentication: true
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
        always: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3
      unauthorized:
        access_vlan_membership_egress: true
```
2-Assign the port_profile to an interface
3-Build
```


### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Adding the key to `eos_cli_config_gen` will not make it work in `eos_designs` automatically, so we have to implement this including adding a test and updating the schema.
It may work, because the schema is just warning you for now (will change to error in 5.0), and because our implementation is lazy so we just "funnel" all the inputs through to `eos_cli_config_gen` on the relevant interfaces.

I will change this issue to a feature request instead of a bug, but thank you for reporting!
