### ISSUE TITLE
fix error with missing uplinks_to_super_spine_interfaces on spines

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#437]
When `uplinks_to_super_spine_interfaces` is not present on spines, Ansible produces an error.
That was introduced when fixing #267 
To fix test if `uplinks_to_super_spine_interfaces` is defined.

**Comment by ClausHolbechArista** [comment]
This branch is outdated, since super-spine implementation has changed a lot since it was created. Most templates have moved around, and you even created a different way of defining the neighbors, so the code is no longer relevant.
Issue is still there, but it is in file eos_l3ls_evpn/templates/fabric/interfaces/super-spine-p2p-interfaces.j2.
To avoid running the code section the extra variable checks should be put up at the check for `type=='spine'`

**Comment by ankudinov** [comment]
closing as the bug is fixed by Claus already
