### ISSUE TITLE
"ip address virtual" vs "ip virtual-router address" option for eVPN

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/ansible-avd#67]
Recall that there are no GARPs for interfaces with "ip address virtual", which could be somewhat problematic for L2 infrastructure that is southbound of the VTEPs.

Of course, removing "ip address virtual" results in chewing up more IP addresses in the entire eVPN fabric.

**Comment by carlbuchmann** [comment]
Comparison of commands and behavior:
https://eos.arista.com/a-comparison-of-virtual-ip-commands/

**Comment by carlbuchmann** [comment]
resolved with PR #132

**Comment by network-ardent** [comment]
From the article in Arista, there seems to be nothing special about it but saving the IP
If you have any other restrictions, please let me know

(We are already aware of the behavior of not issuing GARP)

**Comment by ClausHolbechArista** [comment]
There are also different behaviors for traffic sourced or forwarded by the switch. The article should cover all the differences.
For AVD it is much simpler to use `ip address virtual` since you don't have to provision unique IPs per TOR under the SVI definition.
Also notice if you need to have some kind of L3 peering, you will need `ip virtual-router`.
